### ISSUE TITLE
sawmill模组不兼容

### ISSUE THREAD

**Issue by 1luik** [0999312/SlashBlade_Resharped#4]
[11:42:05] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[11:42:05] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        Index: 3
        Listeners:
                0: NORMAL
                1: ASM: org.embeddedt.modernfix.forge.init.ModernFixForge@4bf2f75a onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@75fd3fd9
                3: ASM: net.mehvahdjukaar.sawmill.forge.SawmillForge@652502d8 dataSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                4: ASM: class dev.xkmc.l2library.init.events.GeneralEventHandler onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                5: ASM: class com.supermartijn642.rechiseled.chiseling.ChiselingRecipeLoader onDataPackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@3c78984f
                7: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onDataSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                8: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@23b3b034
                9: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@329bb1f6
                10: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@2e04438b
                11: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@56460ce4
                12: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@684a2408
                13: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@7b13cf6
                14: ASM: class com.simibubi.create.foundation.events.CommonEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                15: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@b252f90
                16: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@6d62233c
                17: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@727ac625 onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                18: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@543120fc
                19: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@5a69f000
                20: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@78120d72
                21: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@415ba8f
                22: net.minecraftforge.eventbus.EventBus$$Lambda$1725/0x00000122eb7a0000@59fe4c31
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/slashblade@0.1.4/mods.flammpfeil.slashblade.SlashBladeCreativeGroup.fillBlades(SlashBladeCreativeGroup.java:62)
        at TRANSFORMER/slashblade@0.1.4/mods.flammpfeil.slashblade.SlashBladeCreativeGroup.lambda$static$2(SlashBladeCreativeGroup.java:53)
        at TRANSFORMER/forge@47.2.18/net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1627)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710)
        at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:48)
        at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.RecipeSorter.sendOrderToClient(RecipeSorter.java:84)
        at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.forge.SawmillForge.dataSync(SawmillForge.java:37)
        at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.forge.__SawmillForge_dataSync_OnDatapackSyncEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.redirect$chj000$fabric_networking_api_v1$handlePlayerJoin(ServerLoginPacketListenerImpl.java:1063)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 1luik** [comment]
其他mod也报错
